development:
  cloud_name: dgrvu0qjy
  api_key: '871275212533673'
  api_secret: QN0_qPcFB8bCYFcnreFPxItpFZM
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dgrvu0qjy
  api_key: '871275212533673'
  api_secret: QN0_qPcFB8bCYFcnreFPxItpFZM
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dgrvu0qjy
  api_key: '871275212533673'
  api_secret: QN0_qPcFB8bCYFcnreFPxItpFZM
  enhance_image_tag: true
  static_image_support: false
